---
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource

- name: bosh-deployment
  type: docker-image
  source:
    repository: cloudfoundry/bosh-deployment-resource

- name: s3-iam
  type: docker-image
  source:
    repository: 18fgsa/s3-resource

resources:
- name: postfix-config
  type: git
  source:
    uri: ((postfix-config-uri))
    branch: ((postfix-config-branch))

- name: postfix-release
  type: s3-iam
  source:
    bucket: ((s3-bosh-releases-bucket))
    private: true
    regexp: postfix-(.*).tgz
    region_name: ((aws-region))

- name: stemcell-bionic
  type: bosh-io-stemcell
  source:
    name: bosh-aws-xen-hvm-ubuntu-bionic-go_agent

- name: terraform-yaml
  type: s3-iam
  source:
    bucket: ((tf-state-bucket))
    versioned_file: ((tf-state-file))
    region_name: ((aws-region))

- name: terraform-west-yaml
  type: s3-iam
  source:
    bucket: ((tf-state-bucket))
    versioned_file: ((tf-state-west-file))
    region_name: ((aws-region))

- name: terraform-east-yaml
  type: s3-iam
  source:
    bucket: ((tf-state-bucket))
    versioned_file: ((tf-state-east-file))
    region_name: ((aws-east-region))

- name: common-production
  type: s3-iam
  source:
    region_name: ((aws-region))
    bucket: ((private-production-bucket))
    versioned_file: production-postfix.yml

- name: common-production-west
  type: s3-iam
  source:
    region_name: ((aws-region))
    bucket: ((private-production-bucket))
    versioned_file: production-west-postfix.yml

- name: common-production-east
  type: s3-iam
  source:
    region_name: ((aws-east-region))
    bucket: ((private-production-bucket))
    versioned_file: production-east-postfix.yml

- name: postfix-deployment-production
  type: bosh-deployment
  source:
    target: ((production-bosh-target))
    client: ((production-bosh-client))
    client_secret: ((production-bosh-client-secret))
    ca_cert: ((bosh-ca-cert))
    deployment: postfix-production

- name: postfix-deployment-prod-west
  type: bosh-deployment
  source:
    target: ((tooling-west-bosh-target))
    client: ((tooling-west-bosh-client))
    client_secret: ((tooling-west-bosh-client-secret))
    ca_cert: ((bosh-ca-cert))
    deployment: postfix-prod-west

- name: postfix-deployment-prod-east
  type: bosh-deployment
  source:
    target: ((tooling-east-bosh-target))
    client: ((tooling-east-bosh-client))
    client_secret: ((tooling-east-bosh-client-secret))
    ca_cert: ((bosh-ca-cert))
    deployment: postfix-prod-east

- name: slack
  type: slack-notification
  source:
    url: ((slack-webhook-url))

- name: tests-timer
  type: time
  source:
    interval: 10m

jobs:
- name: plan-postfix-production
  serial_groups: [deploy]
  plan:
  - in_parallel:
    - get: stemcell-bionic
      trigger: true
    - get: postfix-config
      trigger: true
    - get: postfix-release
      trigger: true
    - get: terraform-yaml
    - get: common-production
      trigger: true
  - put: postfix-deployment-production
    params:
      manifest: postfix-config/bosh/manifest.yml
      dry_run: true
      stemcells:
      - stemcell-bionic/*.tgz
      releases:
      - postfix-release/*.tgz
      ops_files:
      - postfix-config/bosh/opsfiles/production.yml
      vars_files:
      - terraform-yaml/state.yml
      - common-production/production-postfix.yml
      - postfix-config/bosh/varsfiles/production.yml
  on_success:
    put: slack
    params:
      text: |
        :white_check_mark: Postfix production plan is ready for review
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))
  on_failure:
    put: slack
    params:
      text: |
        :x: FAILED to plan production Postfix
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))

- name: deploy-postfix-production
  serial_groups: [deploy]
  plan:
  - in_parallel:
    - get: postfix-config
      passed: [plan-postfix-production]
    - get: postfix-release
      passed: [plan-postfix-production]
    - get: stemcell-bionic
      passed: [plan-postfix-production]
    - get: terraform-yaml
      passed: [plan-postfix-production]
    - get: common-production
      passed: [plan-postfix-production]
  - put: postfix-deployment-production
    params:
      manifest: postfix-config/bosh/manifest.yml
      stemcells:
      - stemcell-bionic/*.tgz
      releases:
      - postfix-release/*.tgz
      ops_files:
      - postfix-config/bosh/opsfiles/production.yml
      vars_files:
      - terraform-yaml/state.yml
      - common-production/production-postfix.yml
      - postfix-config/bosh/varsfiles/production.yml
  on_success:
    put: slack
    params:
      text: |
        :white_check_mark: Successfully deployed postfix on prodution
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))
  on_failure:
    put: slack
    params:
      text: |
        :x: FAILED to deploy postfix on production
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))

- name: smoke-tests-production
  serial_groups: [deploy]
  plan:
  - in_parallel:
    - get: postfix-config
      passed: [deploy-postfix-production]
      trigger: true
    - get: terraform-yaml
      passed: [deploy-postfix-production]
      trigger: true
    - get: tests-timer
      trigger: true
  - task: smoke-test-cloudgov-sasl
    file: postfix-config/ci/verify-sasl.yml
    params:
      USERNAME: cloudgov@fr.cloud.gov
      PASSWORD: ((cloudgov_pw))
  - task: smoke-test-pages-sasl
    file: postfix-config/ci/verify-sasl.yml
    params:
      USERNAME: pages@fr.cloud.gov
      PASSWORD: ((pages_pw))
  on_success:
    put: slack
    params:
      text: |
        :white_check_mark: Smoke Tests for Postfix on prod PASSED
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-news-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))
  on_failure:
    put: slack
    params:
      text: |
        :x: Smoke Tests for Postfix on prod FAILED
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))

- name: plan-postfix-prod-west
  serial_groups: [deploy]
  plan:
  - in_parallel:
    - get: stemcell-bionic
      trigger: true
    - get: postfix-config
      trigger: true
    - get: postfix-release
      trigger: true
    - get: terraform-yaml
      resource: terraform-west-yaml
    - get: common-production-west
      trigger: true
  - put: postfix-deployment-prod-west
    params: &postfix-west-deploy
      manifest: postfix-config/bosh/manifest.yml
      dry_run: true
      stemcells:
      - stemcell-bionic/*.tgz
      releases:
      - postfix-release/*.tgz
      ops_files:
      - postfix-config/bosh/opsfiles/prod-west.yml
      - postfix-config/bosh/opsfiles/production.yml
      vars_files:
      - terraform-yaml/state.yml
      - common-production-west/production-west-postfix.yml
      - postfix-config/bosh/varsfiles/prod-west.yml
  on_success:
    put: slack
    params:
      text: |
        :white_check_mark: Postfix prod-west plan is ready for review
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))
  on_failure:
    put: slack
    params:
      text: |
        :x: FAILED to plan prod-west Postfix
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))

- name: deploy-postfix-prod-west
  serial_groups: [deploy]
  plan:
  - in_parallel:
    - get: postfix-config
      passed: [plan-postfix-prod-west]
    - get: postfix-release
      passed: [plan-postfix-prod-west]
    - get: stemcell-bionic
      passed: [plan-postfix-prod-west]
    - get: terraform-yaml
      resource: terraform-west-yaml
      passed: [plan-postfix-prod-west]
    - get: common-production-west
      passed: [plan-postfix-prod-west]
  - put: postfix-deployment-prod-west
    params:
      <<: *postfix-west-deploy
      dry_run: false
  on_success:
    put: slack
    params:
      text: |
        :white_check_mark: Successfully deployed postfix on prod-west
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))
  on_failure:
    put: slack
    params:
      text: |
        :x: FAILED to deploy postfix on prod-west
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))

- name: smoke-tests-prod-west
  serial_groups: [deploy]
  plan:
  - in_parallel:
    - get: postfix-config
      passed: [deploy-postfix-prod-west]
      trigger: true
    - get: terraform-yaml
      resource: terraform-west-yaml
      passed: [deploy-postfix-prod-west]
      trigger: true
    - get: tests-timer
      trigger: true
  - task: smoke-test-cloudgov-sasl
    file: postfix-config/ci/verify-sasl.yml
    params:
      USERNAME: cloudgov@fr.cloud.gov
      PASSWORD: ((cloudgov_pw))
  on_success:
    put: slack
    params:
      text: |
        :white_check_mark: Smoke Tests for Postfix on prod-west PASSED
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-news-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))
  on_failure:
    put: slack
    params:
      text: |
        :x: Smoke Tests for Postfix on prod-west FAILED
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))

- name: plan-postfix-prod-east
  serial_groups: [deploy]
  plan:
  - in_parallel:
    - get: stemcell-bionic
      trigger: true
    - get: postfix-config
      trigger: true
    - get: postfix-release
      trigger: true
    - get: terraform-yaml
      resource: terraform-east-yaml
    - get: common-production-east
      trigger: true
  - put: postfix-deployment-prod-east
    params: &postfix-east-deploy
      manifest: postfix-config/bosh/manifest.yml
      dry_run: true
      stemcells:
      - stemcell-bionic/*.tgz
      releases:
      - postfix-release/*.tgz
      ops_files:
      - postfix-config/bosh/opsfiles/prod-east.yml
      - postfix-config/bosh/opsfiles/production.yml
      vars_files:
      - terraform-yaml/state.yml
      - common-production-east/production-east-postfix.yml
      - postfix-config/bosh/varsfiles/prod-east.yml
  on_success:
    put: slack
    params:
      text: |
        :white_check_mark: Postfix prod-east plan is ready for review
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))
  on_failure:
    put: slack
    params:
      text: |
        :x: FAILED to plan prod-east Postfix
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))

- name: deploy-postfix-prod-east
  serial_groups: [deploy]
  plan:
  - in_parallel:
    - get: postfix-config
      passed: [plan-postfix-prod-east]
    - get: postfix-release
      passed: [plan-postfix-prod-east]
    - get: stemcell-bionic
      passed: [plan-postfix-prod-east]
    - get: terraform-yaml
      resource: terraform-east-yaml
      passed: [plan-postfix-prod-east]
    - get: common-production-east
      passed: [plan-postfix-prod-east]
  - put: postfix-deployment-prod-east
    params:
      <<: *postfix-east-deploy
      dry_run: false
  on_success:
    put: slack
    params:
      text: |
        :white_check_mark: Successfully deployed postfix on prod-east
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))
  on_failure:
    put: slack
    params:
      text: |
        :x: FAILED to deploy postfix on prod-east
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))

- name: smoke-tests-prod-east
  serial_groups: [deploy]
  plan:
  - in_parallel:
    - get: postfix-config
      passed: [deploy-postfix-prod-east]
      trigger: true
    - get: terraform-yaml
      resource: terraform-east-yaml
      passed: [deploy-postfix-prod-east]
      trigger: true
    - get: tests-timer
      trigger: true
  - task: smoke-test-cloudgov-sasl
    file: postfix-config/ci/verify-sasl.yml
    params:
      USERNAME: cloudgov@fr.cloud.gov
      PASSWORD: ((cloudgov_pw))
  on_success:
    put: slack
    params:
      text: |
        :white_check_mark: Smoke Tests for Postfix on prod-east PASSED
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-news-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))
  on_failure:
    put: slack
    params:
      text: |
        :x: Smoke Tests for Postfix on prod-east FAILED
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))
