postfix_root_recipient: /dev/null
postfix_mynetworks:
- 10.0.0.0/8
postfix_myhostname: smtp.fr.cloud.gov
postfix_use_tls: true
postfix_dkim_maildomain: cloud.gov
postfix_use_sasl: true
postfix_sasl_users:
  cloudgov: ((cloudgov_pw))
  pages: ((pages_pw))
  cloudgov-billing: ((cloudgovbilling_pw))